In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


print("Бібліотеки успішно підключені!")

Бібліотеки успішно підключені!

In [5]:
np.random.seed(42)

players = 500

player_id = []
for i in range(players):
    player_id.append(f"PLAYER-{1000+i}")

age = np.random.normal(loc=20, scale=5, size=players).astype(int)
hour = np.random.poisson(lam=120, size=players).astype(float)
matches = (hour * np.random.uniform(1.2, 2.5, size=players)).astype(int)
wins = (matches * np.random.uniform(0.3, 0.7, size=players)).astype(int)
kills = (matches * np.random.uniform(2, 10, size=players)).astype(int)
deaths = (matches * np.random.uniform(2, 8, size=players)).astype(int)
spend_money = np.random.exponential(scale=50, size=players).round(2)
ping = np.random.uniform(low=10, high=90, size=players).round(1)
ratings = np.random.randint(1, 11, size=players)

games_genre = {
    'CS GO': 'FPS',
    'DOTA': 'MOBA',
    'The Wincher': 'RPG', 
    'StarCraft': 'Strategy',
    'Rust': 'Survival'}

games = list(games_genre.keys())

select_games = np.random.choice(games, size=players)
select_genre = [games_genre[g] for g in select_games]

df = pd.DataFrame({
    'PlayerID': player_id,
    'Age': age,
    'Game': select_games,
    'Genre': select_genre,
    'HoursPlayed': hour,
    'MatchesPlayed': matches,
    'Wins': wins,
    'Kills': kills,
    'Deaths': deaths,
    'MoneySpent': spend_money,
    'Ping': ping,
    'Rating': ratings
})

In [6]:
df.loc[np.random.choice(df.index, 15, replace=False), 'Ping'] = np.nan
df.loc[np.random.choice(df.index, 10, replace=False), 'MoneySpent'] = np.nan

df.loc[5, 'HoursPlayed'] = 99999.0
df.loc[12, 'HoursPlayed'] = 85000.0

df.loc[25, 'Ping'] = -50.0
df.loc[88, 'Ping'] = 9999.0

df.loc[102, 'MoneySpent'] = 500000.0

df.loc[45, 'Age'] = -5
df.loc[130, 'Age'] = 150

print("--- Початковий датасет із помилками ---")
print(df.info())

--- Початковий датасет із помилками ---
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PlayerID       500 non-null    str
 1   Age            500 non-null    int64
 2   Game           500 non-null    str
 3   Genre          500 non-null    str
 4   HoursPlayed    500 non-null    float64
 5   MatchesPlayed  500 non-null    int64
 6   Wins           500 non-null    int64
 7   Kills          500 non-null    int64
 8   Deaths         500 non-null    int64
 9   MoneySpent     490 non-null    float64
 10  Ping           485 non-null    float64
 11  Rating         500 non-null    int32
dtypes: float64(3), int32(1), int64(5), str(3)
memory usage: 45.1 KB
None

In [8]:
df_cleaned = df.copy()

hours_cap = df_cleaned['HoursPlayed'].quantile(0.99)
money_cap = df_cleaned['MoneySpent'].quantile(0.99)

valid_mask = (
    (df_cleaned['Age'] >= 6) & (df_cleaned['Age'] <= 100) &         
    (df_cleaned['Ping'] >= 0) & (df_cleaned['Ping'] <= 1000) &       
    (df_cleaned['Ping'].notna()) &                                    
    (df_cleaned['HoursPlayed'] <= hours_cap) &                        
    (df_cleaned['MoneySpent'].notna()) &                              
    (df_cleaned['MoneySpent'] <= money_cap)                          
)

df_cleaned = df_cleaned[valid_mask].reset_index(drop=True)

print(f"Видалено рядків із помилками: {len(df) - len(df_cleaned)}")
print(f"Залишилось некорумпованих записів: {len(df_cleaned)}")

Видалено рядків із помилками: 38
Залишилось некорумпованих записів: 462

In [9]:
print("Перші 5 рядків")
display(df_cleaned.head())

Перші 5 рядків

,PlayerID,Age,Game,Genre,HoursPlayed,MatchesPlayed,Wins,Kills,Deaths,MoneySpent,Ping,Rating
0,PLAYER-1000,22,StarCraft,Strategy,125.0,221,73,2065,1280,32.27,75.6,10
1,PLAYER-1001,19,CS GO,FPS,123.0,245,108,2353,720,26.19,76.1,1
2,PLAYER-1002,23,The Wincher,RPG,103.0,249,168,1647,1206,8.79,57.0,4
3,PLAYER-1003,27,CS GO,FPS,111.0,167,94,811,1051,53.42,38.2,7
4,PLAYER-1004,18,StarCraft,Strategy,109.0,148,84,1228,536,177.28,74.0,9

In [10]:
print("Останні 5 рядків")
display(df_cleaned.tail())

Останні 5 рядків

,PlayerID,Age,Game,Genre,HoursPlayed,MatchesPlayed,Wins,Kills,Deaths,MoneySpent,Ping,Rating
457,PLAYER-1495,22,DOTA,MOBA,123.0,206,65,1662,558,116.35,43.1,6
458,PLAYER-1496,14,CS GO,FPS,131.0,177,106,1199,1345,24.16,13.2,7
459,PLAYER-1497,19,Rust,Survival,105.0,183,82,1323,1116,12.19,31.9,10
460,PLAYER-1498,15,CS GO,FPS,140.0,304,138,2770,1577,29.22,86.5,1
461,PLAYER-1499,13,DOTA,MOBA,116.0,149,89,987,327,2.48,86.3,6

In [11]:
print("Випадкові 5 рядків")
display(df_cleaned.sample(5))

Випадкові 5 рядків

,PlayerID,Age,Game,Genre,HoursPlayed,MatchesPlayed,Wins,Kills,Deaths,MoneySpent,Ping,Rating
312,PLAYER-1340,15,The Wincher,RPG,104.0,129,39,577,856,57.32,85.4,2
97,PLAYER-1105,22,CS GO,FPS,112.0,155,58,941,975,46.12,73.9,7
249,PLAYER-1272,25,CS GO,FPS,115.0,235,100,844,988,45.93,29.9,2
324,PLAYER-1353,19,CS GO,FPS,111.0,197,99,1190,429,10.33,80.4,4
426,PLAYER-1460,29,CS GO,FPS,117.0,218,147,1410,1506,70.35,82.8,10

In [12]:
print("Загальна інформація")
df_cleaned.info()

Загальна інформація
<class 'pandas.DataFrame'>
RangeIndex: 462 entries, 0 to 461
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PlayerID       462 non-null    str
 1   Age            462 non-null    int64
 2   Game           462 non-null    str
 3   Genre          462 non-null    str
 4   HoursPlayed    462 non-null    float64
 5   MatchesPlayed  462 non-null    int64
 6   Wins           462 non-null    int64
 7   Kills          462 non-null    int64
 8   Deaths         462 non-null    int64
 9   MoneySpent     462 non-null    float64
 10  Ping           462 non-null    float64
 11  Rating         462 non-null    int32
dtypes: float64(3), int32(1), int64(5), str(3)
memory usage: 41.6 KB

In [13]:
print("Описова інформація")
display(df_cleaned.describe())

Описова інформація

,Age,HoursPlayed,MatchesPlayed,Wins,Kills,Deaths,MoneySpent,Ping,Rating
count,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000,462.000000
mean,19.575758,119.619048,221.865801,110.705628,1333.045455,1104.781385,46.307814,50.093939,5.709957
std,4.977792,11.034255,48.691327,36.030295,593.384082,479.379672,44.366862,23.061315,2.976092
min,6.000000,88.000000,129.000000,39.000000,342.000000,293.000000,0.000000,10.000000,1.000000
25%,16.000000,111.000000,180.250000,84.000000,844.500000,725.000000,13.312500,29.725000,3.000000
50%,20.000000,120.000000,223.000000,106.500000,1233.500000,1054.500000,32.500000,50.350000,6.000000
75%,23.000000,127.000000,258.000000,136.000000,1797.750000,1426.000000,62.717500,71.025000,8.000000
max,39.000000,153.000000,347.000000,221.000000,3018.000000,2487.000000,231.950000,89.700000,10.000000